# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: capsule-gen/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'capsule-gen/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63\x61psule-gen/service.proto\x12\ncapsulegen\x1a\x13\x63ommon/common.proto\"\xa9\x01\n\x16\x43\x61psuleGenerateRequest\x12\x1e\n\x06gender\x18\x01 \x01(\x0e\x32\x0e.common.Gender\x12\x1c\n\x05style\x18\x02 \x01(\x0e\x32\r.common.Style\x12\x1e\n\x06season\x18\x03 \x01(\x0e\x32\x0e.common.Season\x12%\n\x07palette\x18\x04 \x01(\x0e\x32\x0f.common.PaletteH\x00\x88\x01\x01\x42\n\n\x08_palette\"c\n\x17\x43\x61psuleGenerateResponse\x12&\n\x07\x63\x61psule\x18\x01 \x01(\x0b\x32\x13.capsulegen.CapsuleH\x00\x12\x15\n\x0bimage_chunk\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\")\n\x07\x43\x61psule\x12\x1e\n\x04item\x18\x01 \x03(\x0b\x32\x10.capsulegen.Item\"\xdd\x01\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1e\n\x06gender\x18\x02 \x01(\x0e\x32\x0e.common.Gender\x12\x16\n\x0e\x63\x61tegory_group\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x1c\n\x05style\x18\x05 \x01(\x0e\x32\r.common.Style\x12\r\n\x05\x63olor\x18\x06 \x01(\t\x12\x1e\n\x06season\x18\x07 \x01(\x0e\x32\x0e.common.Season\x12\x10\n\x08material\x18\x08 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\t \x01(\t\x12\x0b\n\x03\x65xt\x18\n \x01(\t2q\n\x11\x43\x61psuleGenService\x12\\\n\x0f\x43\x61psuleGenerate\x12\".capsulegen.CapsuleGenerateRequest\x1a#.capsulegen.CapsuleGenerateResponse0\x01\x42$Z\"capsule-me/internal/gen/capsulegenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'capsule_gen.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"capsule-me/internal/gen/capsulegen'
  _globals['_CAPSULEGENERATEREQUEST']._serialized_start=63
  _globals['_CAPSULEGENERATEREQUEST']._serialized_end=232
  _globals['_CAPSULEGENERATERESPONSE']._serialized_start=234
  _globals['_CAPSULEGENERATERESPONSE']._serialized_end=333
  _globals['_CAPSULE']._serialized_start=335
  _globals['_CAPSULE']._serialized_end=376
  _globals['_ITEM']._serialized_start=379
  _globals['_ITEM']._serialized_end=600
  _globals['_CAPSULEGENSERVICE']._serialized_start=602
  _globals['_CAPSULEGENSERVICE']._serialized_end=715
# @@protoc_insertion_point(module_scope)
