# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommon/common.proto\x12\x06\x63ommon*D\n\x06Gender\x12\x16\n\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n\x0bGENDER_MALE\x10\x01\x12\x11\n\rGENDER_FEMALE\x10\x02*T\n\x05Style\x12\x15\n\x11STYLE_UNSPECIFIED\x10\x00\x12\x10\n\x0cSTYLE_CASUAL\x10\x01\x12\x11\n\rSTYLE_CLASSIC\x10\x02\x12\x0f\n\x0bSTYLE_SPORT\x10\x03*l\n\x06Season\x12\x16\n\x12SEASON_UNSPECIFIED\x10\x00\x12\x11\n\rSEASON_WINTER\x10\x01\x12\x11\n\rSEASON_AUTUMN\x10\x02\x12\x11\n\rSEASON_SPRING\x10\x03\x12\x11\n\rSEASON_SUMMER\x10\x04*[\n\x07Palette\x12\x17\n\x13PALETTE_UNSPECIFIED\x10\x00\x12\x10\n\x0cPALETTE_DARK\x10\x01\x12\x11\n\rPALETTE_LIGHT\x10\x02\x12\x12\n\x0ePALETTE_BRIGHT\x10\x03\x42\x19Z\x17\x61pp/internal/gen/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027app/internal/gen/common'
  _globals['_GENDER']._serialized_start=31
  _globals['_GENDER']._serialized_end=99
  _globals['_STYLE']._serialized_start=101
  _globals['_STYLE']._serialized_end=185
  _globals['_SEASON']._serialized_start=187
  _globals['_SEASON']._serialized_end=295
  _globals['_PALETTE']._serialized_start=297
  _globals['_PALETTE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
