services:

  external:
    build:
      context: ./external
      dockerfile: Dockerfile
    container_name: capsule-external
    environment:
      TG_TOKEN: 8419250904:AAE8hbKcfH8SqY4LQP0blN-d5rRlrt39yC8
    volumes:
      - external_combined:/app/combined_images
    restart: unless-stopped

  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capsule-go
    environment:
      TG_TOKEN: 8419250904:AAE8hbKcfH8SqY4LQP0blN-d5rRlrt39yC8
      OUTFIT_SERVICE_URL: http://external:8000/v1/outfits/recommend
    ports:
      - "8080:8080"
    depends_on:
      external:
        condition: service_started
    restart: unless-stopped

volumes:
  external_combined:
